var N = null;var sourcesIndex = {};
sourcesIndex["cfg_if"] = {"name":"","files":["lib.rs"]};
sourcesIndex["ctor"] = {"name":"","files":["lib.rs"]};
sourcesIndex["ghost"] = {"name":"","files":["args.rs","derive.rs","lib.rs","parse.rs","variance.rs","visibility.rs"]};
sourcesIndex["inventory"] = {"name":"","files":["lib.rs"]};
sourcesIndex["inventory_impl"] = {"name":"","files":["lib.rs"]};
sourcesIndex["libc"] = {"name":"","dirs":[{"name":"unix","dirs":[{"name":"linux_like","dirs":[{"name":"linux","dirs":[{"name":"arch","dirs":[{"name":"generic","files":["mod.rs"]}],"files":["mod.rs"]},{"name":"gnu","dirs":[{"name":"b64","dirs":[{"name":"x86_64","files":["align.rs","mod.rs","not_x32.rs"]}],"files":["mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["fixed_width_ints.rs","lib.rs","macros.rs"]};
sourcesIndex["log"] = {"name":"","files":["lib.rs","macros.rs"]};
sourcesIndex["mini_paste"] = {"name":"","files":["lib.rs"]};
sourcesIndex["mini_paste_proc_macro"] = {"name":"","files":["mod.rs"]};
sourcesIndex["proc_macro2"] = {"name":"","files":["detection.rs","fallback.rs","lib.rs","marker.rs","parse.rs","wrapper.rs"]};
sourcesIndex["proc_macro_hack"] = {"name":"","files":["error.rs","iter.rs","lib.rs","parse.rs","quote.rs"]};
sourcesIndex["quote"] = {"name":"","files":["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]};
sourcesIndex["require_unsafe_in_body"] = {"name":"","dirs":[{"name":"utils","files":["macros.rs","mod.rs"]}],"files":["lib.rs"]};
sourcesIndex["safer_ffi"] = {"name":"","dirs":[{"name":"closure","files":["arc.rs","borrowed.rs","boxed.rs","mod.rs"]},{"name":"headers","files":["_mod.rs","definer.rs"]},{"name":"layout","files":["_mod.rs","impls.rs","macros.rs","niche.rs"]},{"name":"string","files":["_mod.rs","slice.rs"]},{"name":"utils","files":["_mod.rs","macros.rs","markers.rs","prelude.rs"]}],"files":["_lib.rs","boxed.rs","c_char.rs","char_p.rs","ptr.rs","slice.rs","tuple.rs","vec.rs"]};
sourcesIndex["safer_ffi_proc_macro"] = {"name":"","files":["c_str.rs","derives.rs","ffi_export.rs","mod.rs"]};
sourcesIndex["syn"] = {"name":"","dirs":[{"name":"gen","files":["clone.rs","gen_helper.rs"]}],"files":["attr.rs","await.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","error.rs","export.rs","expr.rs","ext.rs","file.rs","generics.rs","group.rs","ident.rs","item.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","pat.rs","path.rs","print.rs","punctuated.rs","reserved.rs","sealed.rs","span.rs","spanned.rs","stmt.rs","thread.rs","token.rs","ty.rs","verbatim.rs","whitespace.rs"]};
sourcesIndex["unicode_xid"] = {"name":"","files":["lib.rs","tables.rs"]};
sourcesIndex["uninit"] = {"name":"","dirs":[{"name":"extension_traits","files":["as_out.rs","manually_drop_mut.rs","maybe_uninit.rs","mod.rs"]},{"name":"utils","files":["macros.rs","mod.rs","prelude.rs"]}],"files":["lib.rs","out_ref.rs"]};
createSourceSidebar();
